import { Ionicons } from "@expo/vector-icons";
import { useMutation } from "@tanstack/react-query";
import { Button, Card, Input } from "heroui-native";
import { useMemo, useState } from "react";
import { ScrollView, Text, View } from "react-native";

import { Container } from "@/components/container";
import { orpc } from "@/utils/orpc";

type Message = {
  id: string;
  role: "assistant" | "user";
  content: string;
};

export default function ChatTabScreen() {
  const [input, setInput] = useState("");
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [messages, setMessages] = useState<Message[]>([
    {
      id: "welcome",
      role: "assistant",
      content:
        "Hello, I am Mednex AI. Ask me about procedures, diagnosis support, differential suggestions, or clinical references.",
    },
  ]);

  const canSend = useMemo(() => input.trim().length > 0, [input]);

  const chatMutation = useMutation(
    orpc.chat.mutationOptions({
      onError(error) {
        setErrorMessage(
          error.message || "Unable to reach AI service right now.",
        );
      },
    }),
  );

  async function handleSend() {
    const prompt = input.trim();

    if (!prompt) {
      return;
    }

    const userMessage: Message = {
      id: `${Date.now()}-user`,
      role: "user",
      content: prompt,
    };

    const nextMessages = [...messages, userMessage];

    setMessages(nextMessages);
    setInput("");
    setErrorMessage(null);

    const result = await chatMutation.mutateAsync({
      messages: nextMessages.map((message) => ({
        role: message.role,
        content: message.content,
      })),
    });

    setMessages((current) => [
      ...current,
      {
        id: `${Date.now()}-assistant`,
        role: "assistant",
        content: result.content,
      },
    ]);
  }

  return (
    <Container isScrollable={false} className="p-4">
      <View className="flex-1 gap-3">
        <Card variant="secondary" className="rounded-2xl p-4">
          <Card.Title>AI Clinical Chat</Card.Title>
          <Card.Description>
            Responses are generated by Mednex AI and should be validated against
            your institution guidelines.
          </Card.Description>
        </Card>

        <Card variant="secondary" className="flex-1 rounded-2xl p-3">
          <ScrollView
            className="flex-1"
            contentContainerStyle={{ gap: 10, paddingBottom: 10 }}
            contentInsetAdjustmentBehavior="automatic"
            keyboardShouldPersistTaps="handled"
          >
            {messages.map((message) => (
              <View
                key={message.id}
                className={`max-w-[88%] rounded-xl p-3 ${
                  message.role === "user"
                    ? "self-end bg-primary"
                    : "self-start bg-secondary"
                }`}
              >
                <Text
                  className={
                    message.role === "user"
                      ? "text-primary-foreground"
                      : "text-foreground"
                  }
                >
                  {message.content}
                </Text>
              </View>
            ))}
            {chatMutation.isPending && (
              <View className="self-start rounded-xl bg-secondary p-3">
                <Text className="text-foreground">Thinking...</Text>
              </View>
            )}
          </ScrollView>

          {errorMessage && (
            <Text className="pb-2 text-danger text-sm">{errorMessage}</Text>
          )}

          <View className="flex-row items-center gap-2 pt-2">
            <Input
              value={input}
              onChangeText={setInput}
              placeholder="Ask a clinical question..."
              className="flex-1"
              returnKeyType="send"
              onSubmitEditing={handleSend}
            />
            <Button
              isDisabled={!canSend || chatMutation.isPending}
              onPress={handleSend}
              className="px-4"
            >
              <Ionicons name="send" size={16} color="white" />
            </Button>
          </View>
        </Card>
      </View>
    </Container>
  );
}
